---
title: Laboratory Task 5
---

# 02 PyTorch Basics

**Name:** Rosemarie Ann S. Bajao  
**Course:** BS Data Science  
**Activity:** PyTorch Basics  

---

## Overview

This notebook covers the fundamentals of working with PyTorch tensors, including converting NumPy arrays into tensors, creating tensors directly, changing data types, reshaping, indexing, and performing arithmetic and matrix operations.

These concepts are applied in Laboratory Task 5, which walks through the process of creating a NumPy array, converting it into a tensor, modifying its shape and type, and performing matrix multiplication with another tensor.

## PyTorch Tensors

A **tensor** is a multi-dimensional array, similar to a NumPy `ndarray`, and is the core data structure used in PyTorch. Tensors are used to store the inputs, outputs, and parameters (weights and biases) of a model.

The main advantage tensors have over regular NumPy arrays is that they can run on a GPU or other specialized hardware, which allows much faster computation, especially for large models.

## Converting NumPy Arrays to Tensors

PyTorch tensors can be created directly from existing NumPy arrays using `torch.from_numpy()`. This is useful when data has already been loaded or processed using NumPy, since it avoids having to recreate the data manually.

A tensor created this way shares memory with the original NumPy array, and it keeps the same data type (`dtype`) as the array it came from, unless the type is changed afterward.

## Reshaping and Basic Operations

Tensors can be reshaped into different dimensions using `.reshape()`, as long as the total number of elements stays the same. They also support slicing and indexing similar to NumPy arrays, arithmetic operations (such as squaring values with `.pow()`), and matrix multiplication using functions like `torch.mm()`.

These operations form the basis for how data flows through and is transformed inside a neural network.

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
<h4><strong>Laboratory Task 5</strong></h4>

<ul style="font-family: Times New Roman; text-align:justify; font-size:15px">
<li>Perform Standard Imports</li>
<li>Create a function called <tt>set_seed()</tt> that accepts <tt>seed: int</tt> as a parameter, this function must return nothing but just set the seed to a certain value.</li>
<li>Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the <tt>set_seed()</tt> function and use <tt>42</tt> as the seed parameter.</li>
<li>Create a tensor "x" from the array above</li>
<li>Change the dtype of x from <tt>int32</tt> to <tt>int64</tt></li>
<li>Reshape <tt>x</tt> into a 3x2 tensor<br>There are several ways to do this.</li>
<li>Return the right-hand column of tensor <tt>x</tt></li>
<li>Without changing <tt>x</tt>, return a tensor of square values of <tt>x</tt><br>There are several ways to do this.</li>
<li>Create a tensor <tt>y</tt> with the same number of elements as <tt>x</tt>, that can be matrix-multiplied with <tt>x</tt><br>Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.<br>Think about what shape it should have to permit matrix multiplication.</li>
<li>Find the matrix product of <tt>x</tt> and <tt>y</tt>.</li>
</ul>
</div>

**Step 1 — Standard Imports**

In [1]:
import torch
import numpy as np

**Step 2 — Define set_seed()**

In [2]:
def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)

**Step 3 — Create array arr**

In [3]:
set_seed(42)
arr = np.random.randint(0, 5, size=6).astype('int32')

assert np.array_equal(arr, np.array([3,4,2,4,4,1])), "Oops"
print(arr)

[3 4 2 4 4 1]


**Step 4 — Convert arr to tensor x**

In [4]:
x = torch.from_numpy(arr)
print(x)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


**Step 5 — Change dtype of x**

In [5]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


**Step 6 — Reshape x into 3x2**

In [6]:
x = x.reshape(3,2)
print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


**Step 7 — Right-hand column of x**

In [7]:
print(x[:,1:])

tensor([[4],
        [4],
        [1]])


**Step 8 — Squared values of x (unchanged)**

In [8]:
print(x.pow(2))
print(x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
tensor([[3, 4],
        [2, 4],
        [4, 1]])


**Step 9 — Create tensor y**

In [9]:
set_seed(42)
y = torch.randint(0,5,(2,3))

assert torch.equal(y, torch.tensor([[2, 2, 1],[4, 1, 0]])), "Oops"
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


**Step 10 — Matrix product of x and y**

In [10]:
prod = torch.mm(x,y)
prod

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

Since `set_seed(42)` is called before every random draw, both `arr` and `y` produce the exact same values every time this runs, which is why both `assert` checks pass. The tensor `x` starts as a flat 6-element tensor with dtype `int32`, then gets converted to `int64` before being reshaped into a 3x2 matrix. Slicing out the right-hand column doesn't change `x` itself, and squaring it with `.pow(2)` also leaves `x` unchanged since it returns a new tensor instead of modifying it in place. Since `x` has shape (3,2), `y` is created with shape (2,3) so the two can be matrix-multiplied, giving a final 3x3 result.

## Conclusion

This task covered the basics of working with tensors in PyTorch, from converting a NumPy array into a tensor to adjusting its type and shape, and finally performing matrix multiplication.

Setting a seed before generating random values made the results reproducible, which is why `arr` and `y` matched their expected values in the assertions. Working through the reshaping and slicing steps also showed that operations like `.pow()` don't change the original tensor, they return a new one instead — an important detail when writing PyTorch code.

The final matrix multiplication step also showed why tensor shapes matter: `x` and `y` needed compatible dimensions (3x2 and 2x3) for `torch.mm()` to work, producing a 3x3 output. Overall, this task built a solid foundation for tensor creation and manipulation, which are used throughout the rest of building and training neural networks in PyTorch.